# app配置
app:
  # 日志文件位置
  #logFile: log/ginlog
  logFilePath: log
  logFileName: ginlog
  httpPort: 8000
  # WebSocket端口
  webSocketPort: 8001
  rpcPort: 9001
  httpUrl: 127.0.0.1:8000
  httpUrlForView: littlecurl.xyz:8000
  # WebSocket完整地址
  webSocketUrl: 127.0.0.1:8001
  webSocketUrlForView: littlecurl.xyz:8001/acc


redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConns: 30

mysql:
  dbUser: "root"
  dbPassword: ":123456"
  dbTcp: "@tcp(localhost:3306)"
  #dbName: "/local_db"
  dbName: "/shaohua_db"
  dbParameters: "?charset=utf8mb4"

html:
  title: "聊天首页"
  contentTypeForm: "application/x-www-form-urlencoded"
  sendMessageUrl: "http://littlecurl.xyz:8000/user/sendMessage"
  sendMessageAllUrl: "http://littlecurl.xyz:8000/user/sendMessageAll"
  getUserListUrl: "http://littlecurl.xyz:8000/user/list"
  webSocketUrl: "ws://littlecurl.xyz:8001/acc"
